variables:
  IMAGE_NAME: NetFit

stages:
  - build_image

before_script:
  - docker info

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker compose build --no-cache
