services:
  front:
    container_name: react-app
    image: react-app
    build: 
      context: .
      dockerfile: Dockerfile-front
    volumes:
    - /Client/front-end/src
    - /Client/front-end/node_modules
    - /Client/front-end/public
    ports: 
    - 3000:3000

  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - /Server/node_modules
    ports:
      - 8000:8000

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
#      !!!! Add the environment values for Username and Password for MongoDB HERE !!!!
        MONGO_INITDB_ROOT_USERNAME: #Username goes here
        MONGO_INITDB_ROOT_PASSWORD: #Password goes here
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: #username
      ME_CONFIG_BASICAUTH_PASSWORD: #password goes here
      ME_CONFIG_MONGODB_ADMINUSERNAME: #admin uername goes here
      ME_CONFIG_MONGODB_ADMINPASSWORD: #admin password goes here
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: default
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
