#For the react section of this dockerfile the below was used as a resource
# https://stackoverflow.com/questions/63691203/how-do-i-make-a-react-app-in-docker-compose-container-is-exiting-after-build-st

FROM node:20.9
WORKDIR /usr/app

COPY Client/frontend /usr/app
RUN npm install
 
EXPOSE 3000
 
CMD [ "npm", "run", "dev" ]