name: Docker Image CI

on:
  push:
    branches: [ "main", "Navbar_Parth" ]
  pull_request:
    branches: [ "main",  "Navbar_Parth" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose build